FROM maven:3.8.3-openjdk-20 as builder

WORKDIR /app

COPY ./pom.xml ./pom.xml

RUN mvn dependency:go-offline -B

COPY ./src ./src

RUN mvn clean package

FROM openjdk:20-jdk-alpine

WORKDIR /app

COPY --from=builder /app/target/*.jar ./service.jar

CMD ["java", "-jar", "./service.jar"]