FROM node:14 as builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:latest

COPY --from=builder /app/dist/radar-web-app /usr/share/nginx/html

EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]
